import { useState } from "react";
import Context from "./Context";

const StateByContext = ({ children }) => {
  const [courseVal, setCourseVal] = useState({
    course: "",
    experience: "",
  });

  const [catTechName, setCatTechName] = useState("");
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [logInData, setLogInData] = useState({});
  const [loading, setLoading] = useState(false);
  const [featuredData, setFeaturedData] = useState({});
  const [totalAppliedJobs, setTotalAppliedJobs] = useState("");

  const courses = [
    "MERN STACK",
    "PYTHON",
    "REACT JS",
    "PHP",
    "JAVA",
    ".NET",
    "SOFTWARE TESTING",
    "SALES FORCE",
    "ANDROID",
    "IOS",
    "FLUTTER",
    "DEVOPS",
    "DATA ANALYTICS",
    "DATA SCIENCE",
    "JAVASCRIPT",
    "BOOTSTRAP",
  ];
  const experience = [
    "Fresher",
    "1 Year",
    "2 Year",
    "3 Year",
    "4 Year",
    "5 Year",
    "6 + Year",
  ];

  const testimonials = [
    {
      name: "Margaret Lawson",
      position: "Creative Director",
      image:
        "https://www.technokri.com/assets/img/testmonial/testimonial-founder.png",
      quote:
        "I am at an age where I just want to be fit and healthy. Our bodies are our responsibility! Start caring for your body, and it will care for you. Eat clean, work out hard.",
    },
    {
      name: "Vishal Parmar",
      position: "Creative Director",
      image: "https://www.technokri.com/assets/img/testmonial/3.jpg",
      quote:
        "Staying fit is a lifestyle choice. I believe in regular exercise, clean eating, and mental peace to maintain a healthy balance.",
    },
    {
      name: "John Doe",
      position: "Marketing Head",
      image:
        "https://www.technokri.com/assets/img/testmonial/testimonial-founder.png",
      quote:
        "Fitness is about consistency and motivation. If you stay on track, your body will repay you in the long run. Eat well, work out, and maintain a positive mindset.",
    },
  ];

  const jobs = [
    {
      id: 76,
      companyImage: "admin/uploads/42ca9f8619fa3ce71ea7d230b721a2dc.jpg",
      title: "FLUTTER DEVELOPER",
      hrName: "Dev Sharma",
      hrEmail: "dev77@gmail.com",
      availability: "yes",
      contact: "9827064110",
      technology: "FLUTTER",
      category: "MOBILE APP DEVELOPMENT",
      description:
        "No Bond Policy, 5 Days Working, Excellent Working Environment",
      expiry: "2024-08-31",
      url: "https://www.technokri.com/admin/uploads/42ca9f8619fa3ce71ea7d230b721a2dc.jpg",

      companyName: "CLOUDWAPP TECHNOLOGIES",
      experience: "1 Year",
      posted: "23 days ago",
    },
    {
      id: 75,
      companyImage: "admin/uploads/98279982efd29ba993f37e030318597e.jpg",
      title: "MERN DEVELOPER",
      companyName: "SOFTGRID",
      hrName: "Shweta Sharma",
      technology: "MERN Stack",
      hrEmail: "shweta.sharma@softgrid.com",
      url: "https://www.technokri.com/admin/uploads/98279982efd29ba993f37e030318597e.jpg",
      availability: "yes",
      contact: "9823456789",
      category: "MERN STACK",
      description: "Flexible Working Hours, Great Team Environment",
      expiry: "2024-09-01",
      experience: "Fresher",
      posted: "23 days ago",
    },
    {
      id: 74,
      companyImage: "admin/uploads/8bd78d175560f64ee7ac0b5aafbfe432.jpg",
      title: "PYTHON DEVELOPER",
      hrName: "Ravi Singh",
      availability: "yes",
      url: "https://www.technokri.com/admin/uploads/8bd78d175560f64ee7ac0b5aafbfe432.jpg",

      technology: "PYTHON",
      hrEmail: "ravi.singh@bluecursor.com",
      contact: "9801234567",
      category: "PYTHON",
      description: "Growth-Oriented Role, 5 Days Working",
      expiry: "2024-08-29",
      companyName: "BLUECURSOR INFOTECH PVT. LTD.",
      experience: "2 Year",
      posted: "20 days ago",
    },
    {
      id: 73,
      companyImage: "admin/uploads/4c8bac6c244a97dcebd9faa21eab428f.jpg",
      technology: "SALES FORCE",

      title: "SALESFORCE DEVELOPER",
      hrName: "Amit Roy",
      hrEmail: "amit.roy@omniforce.com",
      contact: "9845671234",
      url: "https://www.technokri.com/admin/uploads/4c8bac6c244a97dcebd9faa21eab428f.jpg",
      availability: "no",
      category: "CRM DEVELOPMENT",
      description: "Friendly Environment, Competitive Salary",
      expiry: "2024-09-15",
      companyName: "OMNIFORCE TECHNOLOGIES",
      experience: "2 Year",
      posted: "18 days ago",
    },
    {
      id: 72,
      companyImage: "admin/uploads/26d3cd8b9a59a1565d2e2b95c0f80f1d.png",
      title: "REACT JS DEVELOPER",
      companyName: "PIXEL TECH",
      technology: "REACT JS",
      url: "https://www.technokri.com/admin/uploads/26d3cd8b9a59a1565d2e2b95c0f80f1d.png",
      availability: "yes",
      hrName: "Priya Kapoor",
      hrEmail: "priya.kapoor@pixeltech.com",
      contact: "9876543210",
      category: "FRONTEND DEVELOPMENT",
      description: "5 Days Working, Learning Opportunities",
      expiry: "2024-09-10",
      experience: "Fresher",
      posted: "22 days ago",
    },
    {
      id: 71,
      companyImage: "admin/uploads/1234abc.jpg",
      title: "JAVA DEVELOPER",
      hrName: "Meena Gupta",
      hrEmail: "meena.gupta@techcode.com",
      contact: "9812345678",
      technology: "JAVA",
      url: "https://www.technokri.com/admin/uploads/f59043560825639a01d61c721fe4459a.jpg",
      availability: "no",
      category: "BACKEND DEVELOPMENT",
      description: "Hybrid Work Model, Team Building Activities",
      expiry: "2024-09-05",
      companyName: "TECHCODE SOLUTIONS",
      experience: "3 Year",
      posted: "15 days ago",
    },
    {
      id: 70,
      companyImage: "admin/uploads/5678def.jpg",
      title: "DEVOPS ENGINEER",
      hrName: "Rahul Khanna",
      hrEmail: "rahul.khanna@devcorp.com",
      url: "https://www.technokri.com/admin/uploads/3cf0b543818be1150f358233036011d5.jpg",
      availability: "no",
      technology: "DEVOPS",

      contact: "9823456780",
      category: "DEVOPS",
      description: "Performance Bonus, Dynamic Work Environment",
      expiry: "2024-09-20",
      companyName: "DEVCORP",
      experience: "1 Year",
      posted: "10 days ago",
    },
    {
      id: 69,
      companyImage: "admin/uploads/9101ghi.jpg",
      title: "JAVASCRIPT",
      url: "https://www.technokri.com/admin/uploads/470de7eba6c8b33c816eda2471f812c4.jpg",
      availability: "no",
      hrName: "Sunita Rao",
      hrEmail: "sunita.rao@webdynamics.com",
      contact: "9876504321",
      category: "JAVASCRIPT",
      technology: "JAVASCRIPT",

      description: "Competitive Salary, Growth-Oriented Team",
      expiry: "2024-09-12",
      companyName: "WEB DYNAMICS",
      experience: "2 Year",
      posted: "12 days ago",
    },
    {
      id: 68,
      companyImage: "admin/uploads/1112jkl.jpg",
      title: "IOS DEVELOPER",
      hrName: "Kunal Sharma",
      hrEmail: "kunal.sharma@backendhub.com",
      contact: "9845678912",
      technology: "IOS",
      availability: "no",
      url: "https://www.technokri.com/admin/uploads/3ae30017764bcff4009afd0490944763.jpg",

      category: "IOS DEVELOPMENT",
      description: "Great Team, Flexible Working Hours",
      expiry: "2024-09-25",
      companyName: "IOS HUB",
      experience: "2 Year",
      posted: "8 days ago",
    },
    {
      id: 67,
      companyImage: "admin/uploads/php_developer.jpg",
      title: "PHP DEVELOPER",
      hrName: "Rajesh Kumar",
      hrEmail: "rajesh.kumar@websolutions.com",
      contact: "9801234560",
      category: "PHP",
      availability: "no",
      technology: "PHP",
      url: "https://www.technokri.com/admin/uploads/53928add6b1876a300bdbf48d288b296.jpg",

      description: "Remote Working, Flexible Hours",
      expiry: "2024-09-30",
      companyName: "WEB SOLUTIONS",
      experience: "1 Year",
      posted: "5 days ago",
    },
    {
      id: 66,
      companyImage: "admin/uploads/dotnet_developer.jpg",
      title: ".NET DEVELOPER",
      hrName: "Rina Patel",
      hrEmail: "rina.patel@codetech.com",
      contact: "9876543211",
      availability: "no",
      url: "https://www.technokri.com/admin/uploads/ffc7553f60708a6d8e91c5e2dcc032f6.jpg",

      category: ".NET",
      technology: ".NET",

      description: "Growth-Oriented Role, 5 Days Working",
      expiry: "2024-09-28",
      companyName: "CODE TECH SOLUTIONS",
      experience: "4 Year",
      posted: "7 days ago",
    },
    {
      id: 65,
      companyImage: "admin/uploads/software_testing.jpg",
      title: "SOFTWARE TEST ENGINEER",
      hrName: "Amit Verma",
      hrEmail: "amit.verma@testhub.com",
      contact: "9812345679",
      category: "SOFTWARE TESTING",
      availability: "no",
      technology: "SOFTWARE TESTING",
      url: "https://www.technokri.com/admin/uploads/e8ad6e3a6fb9410090190a4c8b3f990c.jpg",

      description: "Career Growth, Performance Bonus",
      expiry: "2024-09-27",
      companyName: "TEST HUB",
      experience: "1 Year",
      posted: "10 days ago",
    },
    {
      id: 64,
      companyImage: "admin/uploads/android_developer.jpg",
      title: "ANDROID",
      hrName: "Sonia Gupta",
      url: "https://www.technokri.com/admin/uploads/48fd9f019dd5ecd80f7d826ee5da7142.jpg",
      availability: "no",
      hrEmail: "sonia.gupta@mobiletech.com",
      contact: "9823456781",
      category: "ANDROID",
      description: "Work-Life Balance, Growth Opportunities",
      expiry: "2024-09-24",
      companyName: "ANDROID HUB",
      technology: "ANDROID",

      experience: "2 Year",
      posted: "8 days ago",
    },
    {
      id: 63,
      companyImage: "admin/uploads/ios_developer.jpg",
      title: "DATA SCIENCE",
      technology: "DATA SCIENCE",
      hrName: "Nitin Khurana",
      hrEmail: "nitin.khurana@applelabs.com",
      url: "https://www.technokri.com/admin/uploads/d0dfa8c3b8ed016418934d60c0908401.jpg",

      contact: "9809876543",
      availability: "no",
      category: "DATA SCIENCE",
      description: "Learning Opportunities, Flexible Hours",
      expiry: "2024-09-22",
      companyName: "WORLD SCIENCE CORPS",
      experience: "5 Year",
      posted: "12 days ago",
    },
    {
      id: 62,
      companyImage: "admin/uploads/ios_developer.jpg",
      title: "DATA ANALYTICS",
      technology: "DATA ANALYTICS",
      url: "https://www.technokri.com/admin/uploads/9e4e76c1aa8e65859eb3aa84fdf5742a.jpg",
      availability: "no",
      hrName: "Aamn Shah",
      hrEmail: "aman.shah@applelabs.com",
      contact: "9809876543",
      category: "DATA ANALYTICS",
      description: "Learning Opportunities, Flexible Hours",
      expiry: "2024-09-22",
      companyName: "DATA ANALYTICS",
      experience: "3 Year",
      posted: "12 days ago",
    },

    {
      id: 61,
      companyImage: "admin/uploads/data_science.jpg",
      title: "BOOTSTRAP",
      url: "https://www.technokri.com/admin/uploads/a52c37593327035d70fe7a411fe4f575.jpg",

      hrName: "Priya Sen",
      availability: "no",
      hrEmail: "priya.sen@datasciencehub.com",
      contact: "9845123789",
      category: "BOOTSTRAP",
      description: "5 Days Working, Attractive Salary",
      expiry: "2024-09-18",
      companyName: "HUB",
      experience: "3 Year",
      technology: "BOOTSTRAP",

      posted: "17 days ago",
    },
    {
      id: 60,
      companyImage: "admin/uploads/js_developer.jpg",
      title: "JAVASCRIPT DEVELOPER",
      hrName: "Arjun Malik",
      url: "https://www.technokri.com/admin/uploads/470de7eba6c8b33c816eda2471f812c4.jpg",
      availability: "no",
      hrEmail: "arjun.malik@webdynamics.com",
      contact: "9812347654",
      category: "JAVASCRIPT",
      description: "Dynamic Team, Flexible Hours",
      expiry: "2024-09-15",
      companyName: "WEB DYNAMICS",
      experience: "2 Year",
      technology: "JAVASCRIPT",

      posted: "20 days ago",
    },
    {
      id: 59,
      companyImage: "admin/uploads/bootstrap_expert.jpg",
      title: "ANDROID",
      hrName: "Geeta Pandey",
      hrEmail: "geeta.pandey@designhub.com",
      contact: "9871234560",
      technology: "ANDROID",
      availability: "no",
      category: "ANDROID",
      url: "https://www.technokri.com/admin/uploads/48fd9f019dd5ecd80f7d826ee5da7142.jpg",

      description: "Attractive Salary, Skill Development",
      expiry: "2024-09-13",
      companyName: "ANDROID HUB",
      experience: "1 Year",
      posted: "22 days ago",
    },
    {
      id: 51,
      companyImage: "admin/uploads/mern_developer_04.jpg",
      title: "SENIOR MERN DEVELOPER",
      companyName: "TECHSPACE SOLUTIONS",
      hrName: "Manish Singh",
      hrEmail: "manish.singh@techspace.com",
      contact: "9823456785",
      technology: "MERN Stack",
      url: "https://www.technokri.com/admin/uploads/98279982efd29ba993f37e030318597e.jpg",
      availability: "yes",
      category: "MERN STACK",
      description: "Competitive Salary, Great Team Culture",
      expiry: "2024-09-18",
      experience: "3 Year",
      posted: "2 days ago",
    },
    {
      id: 50,
      companyImage: "admin/uploads/mern_developer_05.jpg",
      title: "MERN STACK DEVELOPER",
      companyName: "INNOVATE INC.",
      hrName: "Sonia Mehta",
      hrEmail: "sonia.mehta@innovate.com",
      contact: "9812345671",
      availability: "yes",
      technology: "MERN Stack",
      category: "MERN STACK",
      description: "Career Growth, Remote Work Options",
      expiry: "2024-09-28",
      experience: "1 Year",
      posted: "3 days ago",
    },
    {
      id: 49,
      companyImage: "admin/uploads/flutter_developer_01.jpg",
      title: "FLUTTER DEVELOPER",
      companyName: "MOBILE SOLUTIONS",
      hrName: "Rakesh Kumar",
      url: "https://www.technokri.com/admin/uploads/42ca9f8619fa3ce71ea7d230b721a2dc.jpg",
      availability: "no",
      hrEmail: "rakesh.kumar@mobilesolutions.com",
      contact: "9823456786",
      technology: "FLUTTER",
      category: "MOBILE APP DEVELOPMENT",
      description: "Flexible Work Hours, Competitive Salary",
      expiry: "2024-09-12",
      experience: "2 Year",
      posted: "4 days ago",
    },
    {
      id: 48,
      companyImage: "admin/uploads/python_developer_01.jpg",
      title: "PYTHON DEVELOPER",
      companyName: "PYTHON INC.",
      hrName: "Maya Sharma",
      hrEmail: "maya.sharma@pythoninc.com",
      contact: "9809876542",
      url: "https://www.technokri.com/admin/uploads/8bd78d175560f64ee7ac0b5aafbfe432.jpg",

      technology: "PYTHON",
      availability: "yes",
      category: "PYTHON DEVELOPMENT",
      description: "Career Development, Learning Opportunities",
      expiry: "2024-09-19",
      experience: "Fresher",
      posted: "6 days ago",
    },
    {
      id: 47,
      companyImage: "admin/uploads/java_developer_01.jpg",
      title: "JUNIOR JAVA DEVELOPER",
      companyName: "CODE HUB",
      hrName: "Ankur Singh",
      url: "https://www.technokri.com/admin/uploads/f59043560825639a01d61c721fe4459a.jpg",
      availability: "no",
      hrEmail: "ankur.singh@codehub.com",
      contact: "9812345672",
      technology: "JAVA",
      category: "BACKEND DEVELOPMENT",
      description: "Great Work-Life Balance, Growth Opportunities",
      expiry: "2024-09-22",
      experience: " Year1",
      posted: "8 days ago",
    },
    {
      id: 46,
      companyImage: "admin/uploads/salesforce_developer_01.jpg",
      title: "SALESFORCE DEVELOPER",
      url: "https://www.technokri.com/admin/uploads/4c8bac6c244a97dcebd9faa21eab428f.jpg",
      availability: "no",
      companyName: "CRM TECHNOLOGIES",
      hrName: "Rohit Tiwari",
      hrEmail: "rohit.tiwari@crmtech.com",
      contact: "9823456787",
      technology: "SALES FORCE",
      category: "CRM DEVELOPMENT",
      description: "Excellent Career Growth, Performance Bonus",
      expiry: "2024-09-24",
      experience: "2 Year",
      posted: "5 days ago",
    },
    {
      id: 45,
      companyImage: "admin/uploads/mern_developer_06.jpg",
      title: "FULL STACK MERN DEVELOPER",
      companyName: "DEV HUB",
      hrName: "Nikita Rao",
      hrEmail: "nikita.rao@devhub.com",
      contact: "9812345673",
      availability: "yes",
      technology: "MERN Stack",
      url: "https://www.technokri.com/admin/uploads/98279982efd29ba993f37e030318597e.jpg",

      category: "MERN STACK",
      description: "Work-Life Balance, Attractive Salary",
      expiry: "2024-09-14",
      experience: "Fresher",
      posted: "6 days ago",
    },
    {
      id: 44,
      companyImage: "admin/uploads/flutter_developer_02.jpg",
      title: "FLUTTER DEVELOPER",
      companyName: "TECH WORLD",
      hrName: "Poonam Joshi",
      url: "https://www.technokri.com/admin/uploads/42ca9f8619fa3ce71ea7d230b721a2dc.jpg",
      availability: "no",
      hrEmail: "poonam.joshi@techworld.com",
      contact: "9823456788",
      technology: "FLUTTER",
      category: "MOBILE APP DEVELOPMENT",
      description: "Career Development, Great Team",
      expiry: "2024-09-17",
      experience: "1 Year",
      posted: "7 days ago",
    },
    {
      id: 43,
      companyImage: "admin/uploads/python_developer_02.jpg",
      title: "SENIOR PYTHON DEVELOPER",
      companyName: "INNOVATIVE SOLUTIONS",
      hrName: "Rajeev Gupta",
      hrEmail: "rajeev.gupta@innovativesolutions.com",
      contact: "9876543210",
      technology: "PYTHON",
      category: "PYTHON DEVELOPMENT",
      url: "https://www.technokri.com/admin/uploads/8bd78d175560f64ee7ac0b5aafbfe432.jpg",
      availability: "no",
      description: "Leadership Opportunities, Learning Environment",
      expiry: "2024-09-30",
      experience: "5 Year",
      posted: "9 days ago",
    },
    {
      id: 42,
      companyImage: "admin/uploads/java_developer_02.jpg",
      title: "JAVA DEVELOPER",
      companyName: "GLOBEX CORPORATION",
      hrName: "Sakshi Yadav",
      hrEmail: "sakshi.yadav@globexcorp.com",
      contact: "9809876543",
      url: "https://www.technokri.com/admin/uploads/f59043560825639a01d61c721fe4459a.jpg",
      availability: "no",
      technology: "JAVA",
      category: "BACKEND DEVELOPMENT",
      description: "Excellent Growth Opportunities, Hybrid Model",
      expiry: "2024-09-29",
      experience: "2 Year",
      posted: "10 days ago",
    },
    {
      id: 41,
      companyImage: "admin/uploads/salesforce_developer_02.jpg",
      title: "SALESFORCE DEVELOPER",
      companyName: "TECH HUB",
      hrName: "Vikram Singh",
      url: "https://www.technokri.com/admin/uploads/4c8bac6c244a97dcebd9faa21eab428f.jpg",
      availability: "no",
      hrEmail: "vikram.singh@techhub.com",
      contact: "9876543211",
      technology: "SALES FORCE",
      category: "CRM DEVELOPMENT",
      description: "Flexible Working Hours, Growth-Oriented Role",
      expiry: "2024-09-26",
      experience: "2 Year",
      posted: "4 days ago",
    },
    {
      id: 40,
      companyImage: "admin/uploads/mern_developer_07.jpg",
      title: "MERN STACK DEVELOPER",
      companyName: "WEB TECH SOLUTIONS",
      hrName: "Amit Patel",
      hrEmail: "amit.patel@webtech.com",
      contact: "9823456789",
      technology: "MERN Stack",
      url: "https://www.technokri.com/admin/uploads/98279982efd29ba993f37e030318597e.jpg",
      availability: "yes",
      category: "MERN STACK",
      description: "Great Learning Opportunities, Competitive Salary",
      expiry: "2024-09-21",
      experience: "2 Year",
      posted: "8 days ago",
    },
    {
      id: 39,
      companyImage: "admin/uploads/flutter_developer_03.jpg",
      title: "FLUTTER DEVELOPER",
      companyName: "APP TECH",
      hrName: "Vishal Sharma",
      url: "https://www.technokri.com/admin/uploads/42ca9f8619fa3ce71ea7d230b721a2dc.jpg",
      availability: "no",
      hrEmail: "vishal.sharma@apptech.com",
      contact: "9823456790",
      technology: "FLUTTER",
      category: "MOBILE APP DEVELOPMENT",
      description: "Work-Life Balance, Performance Bonus",
      expiry: "2024-09-15",
      experience: "2 Year",
      posted: "9 days ago",
    },
    {
      id: 38,
      companyImage: "admin/uploads/python_developer_03.jpg",
      title: "PYTHON DEVELOPER",
      companyName: "SOFTWARE SOLUTIONS",
      hrName: "Neha Verma",
      url: "https://www.technokri.com/admin/uploads/8bd78d175560f64ee7ac0b5aafbfe432.jpg",
      availability: "no",
      hrEmail: "neha.verma@softwaresolutions.com",
      contact: "9801234579",
      technology: "PYTHON",
      category: "PYTHON DEVELOPMENT",
      description: "Dynamic Work Environment, Career Development",
      expiry: "2024-09-23",
      experience: "1 Year",
      posted: "7 days ago",
    },
    {
      id: 37,
      companyImage: "admin/uploads/java_developer_03.jpg",
      title: "JUNIOR JAVA DEVELOPER",
      companyName: "CYBER TECH",
      hrName: "Nitin Kumar",
      hrEmail: "nitin.kumar@cybertech.com",
      url: "https://www.technokri.com/admin/uploads/f59043560825639a01d61c721fe4459a.jpg",
      availability: "no",
      contact: "9812345680",
      technology: "JAVA",
      category: "BACKEND DEVELOPMENT",
      description: "Learning Opportunities, Team Building Activities",
      expiry: "2024-09-10",
      experience: "Fresher",
      posted: "12 days ago",
    },
    {
      id: 36,
      companyImage: "admin/uploads/salesforce_developer_03.jpg",
      title: "SALESFORCE DEVELOPER",
      companyName: "CRM WORLD",
      hrName: "Priya Sharma",
      url: "https://www.technokri.com/admin/uploads/4c8bac6c244a97dcebd9faa21eab428f.jpg",
      availability: "no",
      hrEmail: "priya.sharma@crmworld.com",
      contact: "9876543214",
      technology: "SALES FORCE",
      category: "CRM DEVELOPMENT",
      description: "Hybrid Working Hours, Attractive Salary",
      expiry: "2024-09-19",
      experience: "2 Year",
      posted: "6 days ago",
    },
    {
      id: 35,
      companyImage: "admin/uploads/mern_developer_08.jpg",
      title: "FULL STACK MERN DEVELOPER",
      companyName: "SOFTCODE SOLUTIONS",
      url: "https://www.technokri.com/admin/uploads/98279982efd29ba993f37e030318597e.jpg",
      availability: "yes",
      hrName: "Amit Soni",
      hrEmail: "amit.soni@softcode.com",
      contact: "9812345678",
      technology: "MERN Stack",
      category: "MERN STACK",
      description: "Excellent Work Culture, Career Growth",
      expiry: "2024-09-12",
      experience: "2 Year",
      posted: "8 days ago",
    },
    {
      id: 34,
      companyImage: "admin/uploads/flutter_developer_04.jpg",
      title: "FLUTTER DEVELOPER",
      url: "https://www.technokri.com/admin/uploads/42ca9f8619fa3ce71ea7d230b721a2dc.jpg",
      availability: "no",
      companyName: "MOBILE DEV TECH",
      hrName: "Sushil Kumar",
      hrEmail: "sushil.kumar@mobiledevtech.com",
      contact: "9845123787",
      technology: "FLUTTER",
      category: "MOBILE APP DEVELOPMENT",
      description: "Dynamic Work Environment, Performance Bonus",
      expiry: "2024-09-24",
      experience: "1 Year",
      posted: "7 days ago",
    },
    {
      id: 33,
      companyImage: "admin/uploads/python_developer_04.jpg",
      title: "SENIOR PYTHON DEVELOPER",
      companyName: "TECHWORK SOLUTIONS",
      hrName: "Radhika Patel",
      hrEmail: "radhika.patel@techwork.com",
      contact: "9823456791",
      technology: "PYTHON",
      url: "https://www.technokri.com/admin/uploads/8bd78d175560f64ee7ac0b5aafbfe432.jpg",
      availability: "no",
      category: "PYTHON DEVELOPMENT",
      description: "Leadership Opportunities, Competitive Salary",
      expiry: "2024-09-27",
      experience: "4 Year",
      posted: "8 days ago",
    },
    {
      id: 32,
      companyImage: "admin/uploads/java_developer_04.jpg",
      title: "JAVA DEVELOPER",
      companyName: "DIGITECH SOLUTIONS",
      hrName: "Ravi Verma",
      hrEmail: "ravi.verma@digitech.com",
      contact: "9823456792",
      technology: "JAVA",
      url: "https://www.technokri.com/admin/uploads/f59043560825639a01d61c721fe4459a.jpg",
      availability: "no",
      category: "BACKEND DEVELOPMENT",
      description: "Work-Life Balance, Career Development",
      expiry: "2024-09-20",
      experience: "3 Year",
      posted: "6 days ago",
    },
    {
      id: 31,
      companyImage: "admin/uploads/salesforce_developer_04.jpg",
      title: "SALESFORCE DEVELOPER",
      companyName: "TECHFORCE INC.",
      url: "https://www.technokri.com/admin/uploads/4c8bac6c244a97dcebd9faa21eab428f.jpg",
      availability: "no",
      hrName: "Aishwarya Singh",
      hrEmail: "aishwarya.singh@techforce.com",
      contact: "9812345690",
      technology: "SALES FORCE",
      category: "CRM DEVELOPMENT",
      description: "Great Learning Environment, Performance Bonus",
      expiry: "2024-09-18",
      experience: "2 Year",
      posted: "9 days ago",
    },
  ];
  return (
    <Context.Provider
      value={{
        courses,
        catTechName,
        setCatTechName,
        experience,
        testimonials,
        courseVal,
        setCourseVal,
        isLoggedIn,
        setIsLoggedIn,
        logInData,
        setLogInData,
        loading,
        setLoading,
        featuredData,
        setFeaturedData,
        jobs,
        totalAppliedJobs,
        setTotalAppliedJobs,
      }}
    >
      {children}
    </Context.Provider>
  );
};

export default StateByContext;

// const all = [
//   {

//   }
// ]
